name: PS3Minigames
version: '${project.version}'
main: me.firephoenix.ps3minigames.PS3Minigames
author: NieGestorben

commands:
  build:
    permission: ps3minigames.command.buildmode
    usage: ยง7/build <PLAYER>
  forcestart:
    permission: ps3minigames.command.forcestart
    usage: ยง7/forcestart <MAP>
  forcestop:
    permission: ps3minigames.command.forcestop
    usage: ยง7/forcestop <GAMEID>
  maplist:
    permission: ps3minigames.command.maplist
    usage: ยง7/maplist